package com.agent.core.agent;

import com.agent.core.model.Message;
import com.agent.core.model.TokenUsage;

import java.util.List;

/**
 * Result of an agent execution.
 *
 * @param output       the final output text
 * @param totalSteps   number of steps the agent took
 * @param messages     the complete message list of this run (conversation transcript)
 * @param model        the model that produced the responses, as reported by the provider (null if unknown)
 * @param finishReason the finish reason of the final LLM response, e.g. "stop", "length" (null if unknown)
 * @param llmCallCount number of LLM calls made during this run
 * @param usage        token usage aggregated across all LLM calls of this run
 */
public record AgentResult(
        String output,
        int totalSteps,
        List<Message> messages,
        String model,
        String finishReason,
        int llmCallCount,
        TokenUsage usage
) {

    public AgentResult {
        messages = messages != null ? List.copyOf(messages) : List.of();
        usage = usage != null ? usage : TokenUsage.NONE;
    }

    /**
     * Total input (prompt) tokens consumed by this run.
     */
    public int promptTokens() {
        return (int) usage.promptTokens();
    }

    /**
     * Total output (completion) tokens generated by this run.
     */
    public int completionTokens() {
        return (int) usage.completionTokens();
    }

    /**
     * Total tokens (input + output) consumed by this run.
     */
    public int totalTokens() {
        return (int) usage.totalTokens();
    }
}
