package com.agent.core.model;

/**
 * Token usage metadata returned by the LLM.
 *
 * @param promptTokens        tokens consumed by the input (prompt)
 * @param completionTokens    tokens generated by the model
 * @param totalTokens         promptTokens + completionTokens
 * @param cachedPromptTokens  prompt tokens served from the prompt cache (0 when unknown)
 * @param reasoningTokens     tokens used for internal reasoning, e.g. by reasoning models (0 when unknown)
 */
public record TokenUsage(
        long promptTokens,
        long completionTokens,
        long totalTokens,
        long cachedPromptTokens,
        long reasoningTokens
) {

    /** Shared instance for responses that carry no usage information. */
    public static final TokenUsage NONE = new TokenUsage(0, 0, 0, 0, 0);

    /**
     * Create usage with only the top-level counters; detail counters are zero.
     */
    public static TokenUsage of(long promptTokens, long completionTokens, long totalTokens) {
        return new TokenUsage(promptTokens, completionTokens, totalTokens, 0, 0);
    }

    /**
     * Return the sum of this usage and {@code other}, for aggregating usage across LLM calls.
     */
    public TokenUsage plus(TokenUsage other) {
        return new TokenUsage(
                promptTokens + other.promptTokens,
                completionTokens + other.completionTokens,
                totalTokens + other.totalTokens,
                cachedPromptTokens + other.cachedPromptTokens,
                reasoningTokens + other.reasoningTokens
        );
    }
}
